### ISSUE TITLE
Cursorhold autocommands giving errors

### ISSUE THREAD

**Issue by physicophilic** [bamonroe/rnoweb-nvim#1]
Hi. Thank you for the plugin. Looks interesting, but I can't use it.

I installed it but it gives this error every time I move my cursor

![image](https://user-images.githubusercontent.com/57056860/217836025-dd53d131-9b58-464f-a5d1-28008e49a85d.png)

Also, if I copy paste your user defined commands as they are, then also nvim complains, so I have commented them for now.

**Comment by bamonroe** [comment]
Hi, thanks for the report. Could you please post a minimum working Rnw or tex file where the error still occurs? I can't really figure out what's wrong just from this message.

**Comment by bamonroe** [comment]
No comment in a while, so I'm going to close this.
