### ISSUE TITLE
Something wrong with setup in README.md

### ISSUE THREAD

**Issue by allpandasarecute** [bamonroe/rnoweb-nvim#2]
Just installed with lazy.nvim, but there is a problem
I don't know what to do, some help could be great, thanks.
![2023-07-17_19-07](https://github.com/bamonroe/rnoweb-nvim/assets/89693496/e8726470-f2b9-47b6-8f29-869f349962fd)
![image](https://github.com/bamonroe/rnoweb-nvim/assets/89693496/86ecdb9a-50e4-4131-a31a-0e547b4cfcb0)

**Comment by bamonroe** [comment]
Sorry for the delay, I don't often check GitHub. 
You're right, the README example was broken. I've updated the README with the correct syntax. Also note that if you're just doing a plain text replacement in your document with something like `\newcommand{\placeholder}{MAYBE}`, instances of `\placeholder{}` are now automatically defined and concealed in document with "MAYBE".
